// Metadados (PT-BR + categoria) dos ícones expostos em `categoryIcons.ts`.
// Mantido em arquivo separado para manter o catálogo de componentes enxuto.

export const CATEGORY_ORDER = [
  'Básicos', 'Comida & Bebida', 'Casa & Móveis', 'Transporte & Lugares',
  'Tecnologia', 'Finanças', 'Trabalho', 'Saúde & Pessoas',
  'Natureza & Clima', 'Vestuário', 'Ferramentas', 'Comunicação',
  'Educação', 'Lazer & Mapas', 'Segurança', 'Símbolos & Diversos',
] as const

export const ICONS_BY_CATEGORY: Record<string, string[]> = {
  'Básicos':              ['Tag', 'Bookmark', 'BookmarkSimple', 'Star', 'Heart', 'Smiley',
                           'Folder', 'FolderOpen', 'Folders', 'PushPin'],
  'Comida & Bebida':      ['ShoppingCart', 'ShoppingBag', 'ShoppingBagOpen', 'Storefront', 'Basket',
                           'Coffee', 'ForkKnife', 'Hamburger', 'Pizza', 'Cookie', 'Cake', 'IceCream',
                           'Bread', 'Fish', 'Egg', 'Carrot', 'Cherries', 'Avocado', 'Pepper',
                           'BowlFood', 'BowlSteam', 'Wine', 'BeerStein', 'BeerBottle', 'Martini',
                           'Champagne'],
  'Casa & Móveis':        ['House', 'HouseLine', 'Buildings', 'Building', 'Couch', 'Bed', 'Armchair',
                           'Lamp', 'Bathtub', 'Shower', 'Door', 'ToiletPaper', 'PaintBucket'],
  'Transporte & Lugares': ['Car', 'CarSimple', 'Bus', 'Train', 'Airplane', 'Bicycle', 'Motorcycle',
                           'GasPump', 'Boat', 'Truck', 'Taxi', 'Tractor', 'Scooter',
                           'TreeEvergreen', 'Tree', 'Plant', 'PottedPlant', 'Flower', 'FlowerLotus',
                           'Leaf'],
  'Tecnologia':           ['DeviceMobile', 'DeviceTablet', 'Laptop', 'Desktop', 'Monitor',
                           'Television', 'GameController', 'MusicNote', 'MusicNotes', 'Camera',
                           'Image', 'Book', 'BookOpen', 'Books', 'Newspaper', 'FileText', 'File',
                           'WifiHigh', 'YoutubeLogo', 'VideoCamera', 'Robot', 'Layout', 'Palette',
                           'Headphones', 'Microphone', 'Radio', 'SpeakerHigh', 'HardDrives',
                           'Database', 'Cloud', 'DownloadSimple', 'UploadSimple', 'Bluetooth',
                           'Cpu', 'Printer', 'Keyboard', 'Mouse'],
  'Finanças':             ['CurrencyDollar', 'CreditCard', 'Wallet', 'PiggyBank', 'TrendUp',
                           'TrendDown', 'Money', 'Receipt', 'Percent', 'Coins', 'Calculator',
                           'ChartBar', 'ChartLine', 'ChartPie', 'Bank', 'Vault', 'HandCoins',
                           'Invoice'],
  'Trabalho':             ['Pulse', 'Package', 'Gift', 'Trophy', 'Briefcase', 'Calendar', 'Clock',
                           'MapPin', 'Globe', 'Lightning', 'ClipboardText', 'Presentation', 'Target',
                           'Crown', 'Medal', 'Note', 'NotePencil', 'Notebook'],
  'Saúde & Pessoas':      ['Heartbeat', 'Pill', 'Stethoscope', 'Baby', 'Brain', 'Ear', 'Syringe',
                           'Barbell', 'Person', 'PersonSimpleRun', 'Dog', 'Cat', 'PawPrint', 'Eye',
                           'EyeSlash', 'Thermometer', 'Bone', 'FirstAid', 'FirstAidKit', 'Tooth'],
  'Natureza & Clima':     ['Drop', 'Fire', 'Wind', 'Sun', 'Moon', 'Waves', 'Snowflake', 'CloudRain',
                           'CloudSnow', 'CloudSun', 'SunHorizon', 'Rainbow', 'Mountains', 'Tent',
                           'Compass', 'Bug', 'Bird', 'Butterfly'],
  'Vestuário':            ['Umbrella', 'TShirt', 'Pants', 'Sneaker', 'Watch', 'Eyeglasses',
                           'Sunglasses', 'Scissors', 'Diamond', 'Sparkle', 'Handbag', 'BaseballCap'],
  'Ferramentas':          ['Wrench', 'Gear', 'Sliders', 'Funnel', 'MagnifyingGlass', 'Bell',
                           'BellRinging', 'Hammer', 'PaintBrush', 'Plug', 'Lock', 'LockOpen', 'Key',
                           'Toolbox', 'Screwdriver'],
  'Comunicação':          ['Envelope', 'EnvelopeOpen', 'ChatCircle', 'ChatText', 'Phone',
                           'PhoneCall', 'Users', 'User', 'UserPlus', 'UserMinus', 'UserCircle',
                           'UserCheck', 'PaperPlane', 'Tray', 'At', 'Hash', 'Share', 'ShareNetwork',
                           'ThumbsUp', 'ThumbsDown', 'Megaphone'],
  'Educação':             ['GraduationCap', 'Student', 'Backpack', 'Pencil', 'PencilSimple',
                           'PenNib', 'Ruler', 'Eraser', 'ChalkboardTeacher'],
  'Lazer & Mapas':        ['Confetti', 'Popcorn', 'FilmSlate', 'MapTrifold', 'NavigationArrow',
                           'Anchor', 'Sailboat', 'PuzzlePiece', 'DiceFour', 'DiceFive', 'DiceSix'],
  'Segurança':            ['Scales', 'Shield', 'ShieldCheck', 'ShieldWarning'],
  'Símbolos & Diversos':  ['Question', 'WarningCircle', 'Warning', 'XCircle', 'Ticket', 'Lightbulb',
                           'ArrowsClockwise', 'Trash', 'CheckCircle', 'Info', 'Shapes', 'Circle',
                           'Square', 'Triangle', 'Hexagon'],
}

export const ICON_PT: Record<string, string> = {
  Tag: 'Etiqueta', Bookmark: 'Marcador', BookmarkSimple: 'Marcador Simples', Star: 'Estrela',
  Heart: 'Coração', Smiley: 'Sorriso', Folder: 'Pasta', FolderOpen: 'Pasta Aberta',
  Folders: 'Pastas', PushPin: 'Alfinete',
  ShoppingCart: 'Carrinho', ShoppingBag: 'Sacola', ShoppingBagOpen: 'Sacola Aberta',
  Storefront: 'Loja', Basket: 'Cesta', Coffee: 'Café', ForkKnife: 'Talheres',
  Hamburger: 'Hambúrguer', Pizza: 'Pizza', Cookie: 'Biscoito', Cake: 'Bolo', IceCream: 'Sorvete',
  Bread: 'Pão', Fish: 'Peixe', Egg: 'Ovo', Carrot: 'Cenoura', Cherries: 'Cerejas',
  Avocado: 'Abacate', Pepper: 'Pimenta', BowlFood: 'Tigela de Comida', BowlSteam: 'Tigela Quente',
  Wine: 'Vinho', BeerStein: 'Caneca de Cerveja', BeerBottle: 'Garrafa de Cerveja',
  Martini: 'Martini', Champagne: 'Champanhe',
  House: 'Casa', HouseLine: 'Casa', Buildings: 'Prédios', Building: 'Prédio', Car: 'Carro',
  CarSimple: 'Carro', Bus: 'Ônibus', Train: 'Trem', Airplane: 'Avião', Bicycle: 'Bicicleta',
  Motorcycle: 'Moto', GasPump: 'Posto de Combustível', Boat: 'Barco', Truck: 'Caminhão',
  Taxi: 'Táxi', Tractor: 'Trator', Scooter: 'Patinete', TreeEvergreen: 'Pinheiro',
  Tree: 'Árvore', Plant: 'Planta', PottedPlant: 'Vaso de Planta', Flower: 'Flor',
  FlowerLotus: 'Flor de Lótus', Leaf: 'Folha', Couch: 'Sofá', Bed: 'Cama', Armchair: 'Poltrona',
  Lamp: 'Luminária', Bathtub: 'Banheira', Shower: 'Chuveiro', Door: 'Porta',
  ToiletPaper: 'Papel Higiênico', PaintBucket: 'Balde de Tinta',
  DeviceMobile: 'Celular', DeviceTablet: 'Tablet', Laptop: 'Notebook', Desktop: 'Computador',
  Monitor: 'Monitor', Television: 'TV', GameController: 'Controle', MusicNote: 'Música',
  MusicNotes: 'Músicas', Camera: 'Câmera', Image: 'Imagem', Book: 'Livro',
  BookOpen: 'Livro Aberto', Books: 'Livros', Newspaper: 'Jornal', FileText: 'Arquivo',
  File: 'Arquivo', WifiHigh: 'Wi-Fi', YoutubeLogo: 'YouTube', VideoCamera: 'Filmadora',
  Robot: 'Robô', Layout: 'Layout', Palette: 'Paleta', Headphones: 'Fones',
  Microphone: 'Microfone', Radio: 'Rádio', SpeakerHigh: 'Alto-falante', HardDrives: 'HD',
  Database: 'Banco de Dados', Cloud: 'Nuvem', DownloadSimple: 'Download', UploadSimple: 'Upload',
  Bluetooth: 'Bluetooth', Cpu: 'Processador', Printer: 'Impressora', Keyboard: 'Teclado',
  Mouse: 'Mouse',
  CurrencyDollar: 'Cifrão', CreditCard: 'Cartão', Wallet: 'Carteira', PiggyBank: 'Cofrinho',
  TrendUp: 'Alta', TrendDown: 'Baixa', Money: 'Dinheiro', Receipt: 'Recibo',
  Percent: 'Porcentagem', Coins: 'Moedas', Calculator: 'Calculadora', ChartBar: 'Gráfico Barras',
  ChartLine: 'Gráfico Linhas', ChartPie: 'Gráfico Pizza', Bank: 'Banco', Vault: 'Cofre',
  HandCoins: 'Pagamento', Invoice: 'Fatura',
  Pulse: 'Atividade', Package: 'Pacote', Gift: 'Presente', Trophy: 'Troféu', Briefcase: 'Maleta',
  Calendar: 'Calendário', Clock: 'Relógio', MapPin: 'Localização', Globe: 'Globo',
  Lightning: 'Raio', ClipboardText: 'Lista', Presentation: 'Apresentação', Target: 'Alvo',
  Crown: 'Coroa', Medal: 'Medalha', Note: 'Nota', NotePencil: 'Editar Nota', Notebook: 'Caderno',
  Heartbeat: 'Batimento', Pill: 'Pílula', Stethoscope: 'Estetoscópio', Baby: 'Bebê',
  Brain: 'Cérebro', Ear: 'Orelha', Syringe: 'Seringa', Barbell: 'Haltere', Person: 'Pessoa',
  PersonSimpleRun: 'Corrida', Dog: 'Cachorro', Cat: 'Gato', PawPrint: 'Pegada', Eye: 'Olho',
  EyeSlash: 'Olho Fechado', Thermometer: 'Termômetro', Bone: 'Osso',
  FirstAid: 'Primeiros Socorros', FirstAidKit: 'Kit Médico', Tooth: 'Dente',
  Drop: 'Gota', Fire: 'Fogo', Wind: 'Vento', Sun: 'Sol', Moon: 'Lua', Waves: 'Ondas',
  Snowflake: 'Floco de Neve', CloudRain: 'Chuva', CloudSnow: 'Neve', CloudSun: 'Sol e Nuvem',
  SunHorizon: 'Pôr do Sol', Rainbow: 'Arco-íris', Mountains: 'Montanhas', Tent: 'Barraca',
  Compass: 'Bússola', Bug: 'Inseto', Bird: 'Pássaro', Butterfly: 'Borboleta',
  Umbrella: 'Guarda-chuva', TShirt: 'Camiseta', Pants: 'Calça', Sneaker: 'Tênis', Watch: 'Relógio',
  Eyeglasses: 'Óculos', Sunglasses: 'Óculos de Sol', Scissors: 'Tesoura', Diamond: 'Diamante',
  Sparkle: 'Brilho', Handbag: 'Bolsa', BaseballCap: 'Boné',
  Wrench: 'Chave Inglesa', Gear: 'Engrenagem', Sliders: 'Controles', Funnel: 'Filtro',
  MagnifyingGlass: 'Buscar', Bell: 'Sino', BellRinging: 'Sino Tocando', Hammer: 'Martelo',
  PaintBrush: 'Pincel', Plug: 'Tomada', Lock: 'Cadeado', LockOpen: 'Destrancado', Key: 'Chave',
  Toolbox: 'Caixa de Ferramentas', Screwdriver: 'Chave de Fenda',
  Envelope: 'Email', EnvelopeOpen: 'Email Aberto', ChatCircle: 'Mensagem', ChatText: 'Conversa',
  Phone: 'Telefone', PhoneCall: 'Chamada', Users: 'Usuários', User: 'Usuário',
  UserPlus: 'Adicionar Usuário', UserMinus: 'Remover Usuário', UserCircle: 'Perfil',
  UserCheck: 'Usuário Verificado', PaperPlane: 'Enviar', Tray: 'Caixa de Entrada', At: 'Arroba',
  Hash: 'Hashtag', Share: 'Compartilhar', ShareNetwork: 'Rede de Compartilhamento',
  ThumbsUp: 'Curtir', ThumbsDown: 'Não Curtir', Megaphone: 'Megafone',
  GraduationCap: 'Formatura', Student: 'Estudante', Backpack: 'Mochila', Pencil: 'Lápis',
  PencilSimple: 'Lápis', PenNib: 'Caneta', Ruler: 'Régua', Eraser: 'Borracha',
  ChalkboardTeacher: 'Professor',
  Confetti: 'Festa', Popcorn: 'Pipoca', FilmSlate: 'Claquete', MapTrifold: 'Mapa',
  NavigationArrow: 'Navegação', Anchor: 'Âncora', Sailboat: 'Veleiro',
  PuzzlePiece: 'Quebra-cabeça', DiceFour: 'Dado 4', DiceFive: 'Dado 5', DiceSix: 'Dado 6',
  Scales: 'Balança', Shield: 'Escudo', ShieldCheck: 'Escudo Verificado',
  ShieldWarning: 'Escudo Alerta',
  Question: 'Ajuda', WarningCircle: 'Alerta', Warning: 'Aviso', XCircle: 'Cancelar',
  Ticket: 'Ingresso', Lightbulb: 'Lâmpada', ArrowsClockwise: 'Atualizar', Trash: 'Lixeira',
  CheckCircle: 'Concluído', Info: 'Informação', Shapes: 'Formas', Circle: 'Círculo',
  Square: 'Quadrado', Triangle: 'Triângulo', Hexagon: 'Hexágono',
}

/** Remove acentos e baixa caixa para busca case/diacritic-insensitive. */
export function normalize(s: string): string {
  return s.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLowerCase()
}

/** Retorna o nome em PT-BR (cai no nome em inglês se não houver tradução). */
export function getIconLabel(name: string): string {
  return ICON_PT[name] ?? name
}
